### ISSUE TITLE
Submitting abstract to Open Science Festival (deadline 11 July)

### ISSUE THREAD

**Issue by EstherPlomp** [EstherPlomp/TNW-Tracking#2]
Hi all! 

I think it would be nice to have a session at the [Open Science Festival ](https://www.opensciencefestival.nl/en) in October in Maastricht. 

I'm aiming for a 1 hour session and I set up the abstract in the [GitHub repository](https://github.com/EstherPlomp/TNW-Tracking/blob/main/abstract-OSF.md).

Please do edit as you like + add your name to the submission if you want to get more involved in the session organisation. Unfortunately the deadline is rapidly approaching: 11 July. **Please make any changes/suggestions by 10 July - 20:00**, so that I can submit it on 10 July or early 11 July. Thank you!

@meronvermaas - would you be happy to present your work during the session? Perhaps you could reuse your eScience Fellowship presentation? 
@c-martinez - Do you have time/willpower to co-organise the session or are you happy for me to take the lead?
@NemoAndrea - will you attend the OSF and if so, are you happy to participate in the session?

I'll leave Azin out of communications right now as she is attending conferences - hopefully names/abstracts can be updated later if needed :) 

Thanks all!

Esther

**Comment by c-martinez** [comment]
Hey @EstherPlomp,

Nice initiative! Deadline is indeed very soon, so will try to contribute it as soon as possible. I am happy for you to take the lead, and I will chip in where I can.

Quickly reading through the proposal, I do think it might be good to point to initiatives that are doing something to advance/change research assessment (https://coara.eu/agreement/the-commitments/, https://adore.software/declaration/ (recommendations 7,8,9), https://hidden-ref.org/?) and tools that already try to track research objects (specifically software, https://research-software-directory.org/).

Best,
Carlos

**Comment by EstherPlomp** [comment]
Thank you @c-martinez for the quick reply and feedback! I updated the text to include you, and Meron, as session organisers. I updated the text to include your feedback as well - also feel free to edit yourself if you have further input!

**Comment by NemoAndrea** [comment]
I will be at the OSF this year and I'll be sure to attend and participate in the session 😃.

**Comment by EstherPlomp** [comment]
Thanks all! I listed everyone as a session organiser and myself and Meron as presenter! I just submitted the proposal so I'll close this issue for now. Fingers crossed :)

**Comment by c-martinez** [comment]
Thanks, Esther!
